language: python
python:
  - "3.3"
  - "3.4"
  # - nightly
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -r requirements-tests.txt --use-mirrors
  - python setup.py develop
  - wget https://dl.bintray.com/mitchellh/consul/0.5.0_linux_amd64.zip
  - unzip 0.5.0_linux_amd64.zip
before_script:
  - export PATH=$PATH:$PWD
script:
  - py.test
