#!/usr/bin/env python3

import sys
import os


# Get the project root dir, which is the parent dir of this
sys.path.insert(0, os.path.abspath('..'))
sys.path.append(os.path.abspath('_exts'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = '1.3'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.intersphinx',
              'sphinx.ext.napoleon',
              'pyspecific']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'
master_doc = 'index'
project = 'AIO Consul'
copyright = '2015, Xavier Barbosa'
author = 'Xavier Barbosa'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.3'
# The full version, including alpha/beta/rc tags.
release = '0.3'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
add_module_names = False

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

import alabaster
extensions.append('alabaster')
html_theme = 'alabaster'
html_theme_path = [alabaster.get_path()]
html_theme_options = {
    'github_user': 'johnnoone',
    'github_repo': 'aioconsul',
    'github_button': True,
    'github_banner': True,
    'travis_button': True,
    'show_powered_by': False,
}
html_sidebars = {
    '**': [
        'about.html', 'navigation.html', 'searchbox.html',
    ]
}


napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = True
napoleon_use_ivar = True
napoleon_use_param = True
napoleon_use_rtype = False



# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = 'AIO Consul documentation'

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
htmlhelp_basename = 'AIOConsuldoc'


intersphinx_mapping = {'python': ('https://docs.python.org/3.4', None)}

#  Options for LaTeX output

latex_elements = {
    'papersize': 'a4paper',
}

latex_documents = [
  (master_doc, 'AIOConsul.tex', 'AIO Consul Documentation',
   'Xavier Barbosa', 'manual'),
]


#  Options for manual page output

man_pages = [
    (master_doc, 'aioconsul', 'AIO Consul Documentation',
     [author], 1)
]


#  Options for Texinfo output

texinfo_documents = [
  (master_doc, 'AIOConsul', 'AIO Consul Documentation',
   author, 'AIOConsul', 'One line description of project.',
   'Miscellaneous'),
]
